import type { LearningDomain } from "./types";

const yt = (q: string) =>
  `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`;

export const LEARNING_DOMAINS: LearningDomain[] = [
  {
    id: "dsa",
    title: "Data Structures & Algorithms",
    emoji: "🧮",
    gradient: "from-violet-600 via-fuchsia-600 to-cyan-500",
    accent: "text-fuchsia-600 dark:text-fuchsia-400",
    description: "Core patterns for interviews and problem solving — arrays to DP.",
    topics: [
      {
        id: "arrays",
        title: "Arrays & Prefix Sums",
        summary: "Indexing, sliding window basics, prefix/difference arrays.",
        level: "Beginner",
        duration: "2–3 h",
        tags: ["arrays", "complexity"],
        studyPoints: [
          "0-based vs 1-based indexing; bounds checks.",
          "Prefix sum: O(1) range sums after O(n) preprocess.",
          "Two pointers on sorted arrays for pair/triplet problems.",
          "Watch for off-by-one in loops and subarray bounds.",
        ],
        geeksForGeeks: [
          { label: "Array Data Structure", href: "https://www.geeksforgeeks.org/array-data-structure/" },
          { label: "Prefix Sum", href: "https://www.geeksforgeeks.org/prefix-sum-array-implementation-applications/" },
        ],
        youtube: [
          { label: "Search: array algorithms tutorial", href: yt("array algorithms two pointers prefix sum") },
          { label: "Search: NeetCode arrays", href: yt("NeetCode arrays") },
        ],
      },
      {
        id: "strings",
        title: "Strings & Parsing",
        summary: "Immutability, frequency maps, palindromes, rolling hash intro.",
        level: "Beginner",
        duration: "2–3 h",
        tags: ["strings"],
        studyPoints: [
          "Character counts with array (ASCII) or map (Unicode).",
          "Two-pointer palindrome checks.",
          "Avoid repeated concatenation in loops (use array join / StringBuilder pattern).",
        ],
        geeksForGeeks: [
          { label: "Strings in Programming", href: "https://www.geeksforgeeks.org/c-programming-strings/" },
          { label: "Anagram", href: "https://www.geeksforgeeks.org/check-whether-two-strings-are-anagram-of-each-other/" },
        ],
        youtube: [{ label: "Search: string algorithms", href: yt("string algorithms interview") }],
      },
      {
        id: "hashmaps",
        title: "Hash Maps & Sets",
        summary: "Frequency, deduplication, complement pairs, collision intuition.",
        level: "Beginner",
        duration: "2 h",
        tags: ["hashmaps"],
        studyPoints: [
          "Average O(1) lookup; worst case depends on buckets.",
          "Set vs map: existence vs key→value.",
          "Trade memory for time on search problems.",
        ],
        geeksForGeeks: [
          { label: "Hashing", href: "https://www.geeksforgeeks.org/hashing-data-structure/" },
          { label: "HashMap vs TreeMap", href: "https://www.geeksforgeeks.org/difference-between-hashmap-and-treemap/" },
        ],
        youtube: [{ label: "Search: hash map interview", href: yt("hash map coding interview") }],
      },
      {
        id: "linkedlists",
        title: "Linked Lists",
        summary: "Singly/doubly, cycles, reversal, merge sorted.",
        level: "Beginner",
        duration: "2–3 h",
        tags: ["linkedlists"],
        studyPoints: [
          "Dummy head simplifies insertion at head.",
          "Floyd cycle detection (two speeds).",
          "Reversal: iterative three-pointer pattern.",
        ],
        geeksForGeeks: [
          { label: "Linked List", href: "https://www.geeksforgeeks.org/data-structures/linked-list/" },
          { label: "Reverse a linked list", href: "https://www.geeksforgeeks.org/reverse-a-linked-list/" },
        ],
        youtube: [{ label: "Search: linked list reversal", href: yt("reverse linked list explained") }],
      },
      {
        id: "stacks-queues",
        title: "Stacks & Queues",
        summary: "LIFO/FIFO, monotonic stack, BFS queue.",
        level: "Intermediate",
        duration: "3 h",
        tags: ["stacks", "queues"],
        studyPoints: [
          "Stack: parentheses, DFS, monotonic for next-greater.",
          "Queue: BFS level-order processing.",
          "Deque for sliding window max.",
        ],
        geeksForGeeks: [
          { label: "Stack Data Structure", href: "https://www.geeksforgeeks.org/stack-data-structure/" },
          { label: "Queue Data Structure", href: "https://www.geeksforgeeks.org/queue-data-structure/" },
        ],
        youtube: [{ label: "Search: stack queue DSA", href: yt("stack queue data structure algorithms") }],
      },
      {
        id: "trees",
        title: "Trees & BST",
        summary: "Traversals, height, BST property, common patterns.",
        level: "Intermediate",
        duration: "4 h",
        tags: ["trees"],
        studyPoints: [
          "Preorder / inorder / postorder; know when each helps.",
          "BST inorder → sorted order.",
          "Height vs depth; balance affects complexity.",
        ],
        geeksForGeeks: [
          { label: "Binary Tree", href: "https://www.geeksforgeeks.org/binary-tree-data-structure/" },
          { label: "Binary Search Tree", href: "https://www.geeksforgeeks.org/binary-search-tree-data-structure/" },
        ],
        youtube: [{ label: "Search: binary tree tutorial", href: yt("binary tree traversal tutorial") }],
      },
      {
        id: "graphs",
        title: "Graphs",
        summary: "Adjacency list/matrix, BFS/DFS, shortest paths basics.",
        level: "Intermediate",
        duration: "4–5 h",
        tags: ["graphs"],
        studyPoints: [
          "Represent sparse graphs with adjacency lists.",
          "BFS for unweighted shortest path.",
          "DFS for connectivity, cycle (directed), topological sort.",
        ],
        geeksForGeeks: [
          { label: "Graph Data Structure", href: "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/" },
          { label: "Dijkstra’s algorithm", href: "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/" },
        ],
        youtube: [{ label: "Search: graph algorithms", href: yt("graph algorithms BFS DFS Dijkstra") }],
      },
      {
        id: "sorting-searching",
        title: "Sorting & Searching",
        summary: "Comparison sorts, binary search variants.",
        level: "Intermediate",
        duration: "3 h",
        tags: ["sorting", "searching"],
        studyPoints: [
          "Merge sort stable O(n log n); quicksort average O(n log n).",
          "Binary search on answer (min feasible) pattern.",
          "Lower/upper bound for duplicates.",
        ],
        geeksForGeeks: [
          { label: "Sorting Algorithms", href: "https://www.geeksforgeeks.org/sorting-algorithms/" },
          { label: "Binary Search", href: "https://www.geeksforgeeks.org/binary-search/" },
        ],
        youtube: [{ label: "Search: binary search patterns", href: yt("binary search algorithm patterns") }],
      },
      {
        id: "dynamic-programming",
        title: "Dynamic Programming",
        summary: "Memoization, tabulation, knapsack, LCS patterns.",
        level: "Advanced",
        duration: "5+ h",
        tags: ["dp"],
        studyPoints: [
          "Identify overlapping subproblems + optimal substructure.",
          "Top-down vs bottom-up; state = dimensions.",
          "Start with brute recursion, then memo.",
        ],
        geeksForGeeks: [
          { label: "Dynamic Programming", href: "https://www.geeksforgeeks.org/dynamic-programming/" },
          { label: "0/1 Knapsack", href: "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/" },
        ],
        youtube: [{ label: "Search: DP for beginners", href: yt("dynamic programming tutorial beginners") }],
      },
      {
        id: "greedy",
        title: "Greedy Algorithms",
        summary: "Local optimal choices, exchange arguments, scheduling.",
        level: "Intermediate",
        duration: "2–3 h",
        tags: ["greedy"],
        studyPoints: [
          "Prove greedy stays ahead or exchange argument.",
          "Classic: activity selection, Huffman (concept).",
          "When greedy fails, consider DP.",
        ],
        geeksForGeeks: [
          { label: "Greedy Algorithms", href: "https://www.geeksforgeeks.org/greedy-algorithms/" },
          { label: "Activity Selection Problem", href: "https://www.geeksforgeeks.org/activity-selection-problem-greedy-algo-1/" },
        ],
        youtube: [{ label: "Search: greedy algorithms", href: yt("greedy algorithm activity selection") }],
      },
    ],
  },
  {
    id: "cyber",
    title: "Cybersecurity",
    emoji: "🛡️",
    gradient: "from-emerald-600 via-teal-500 to-cyan-400",
    accent: "text-emerald-600 dark:text-emerald-400",
    description: "Foundations through incident response — practical security literacy.",
    topics: [
      {
        id: "sec-fundamentals",
        title: "Security Fundamentals",
        summary: "CIA, threats, vulnerabilities, risk, controls.",
        level: "Beginner",
        duration: "2 h",
        tags: ["fundamentals", "risk"],
        studyPoints: ["CIA triad", "Risk = f(threat, vulnerability, impact)", "Defense in depth"],
        geeksForGeeks: [{ label: "Cyber Security Tutorial", href: "https://www.geeksforgeeks.org/cyber-security-tutorial/" }],
        youtube: [{ label: "Search: cybersecurity fundamentals", href: yt("cybersecurity fundamentals CIA triad") }],
      },
      {
        id: "cryptography",
        title: "Cryptography Essentials",
        summary: "Symmetric vs asymmetric, hashes, TLS role.",
        level: "Beginner",
        duration: "3 h",
        tags: ["crypto"],
        studyPoints: ["AES vs RSA use cases", "Hash ≠ encryption", "TLS sits above TCP"],
        geeksForGeeks: [{ label: "Cryptography Introduction", href: "https://www.geeksforgeeks.org/cryptography-and-its-types/" }],
        youtube: [{ label: "Search: TLS explained", href: yt("TLS handshake explained") }],
      },
      {
        id: "network-security",
        title: "Network Security",
        summary: "Firewalls, IDS/IPS, segmentation, TLS.",
        level: "Intermediate",
        duration: "3 h",
        tags: ["networksec"],
        studyPoints: ["Default deny", "East-west vs north-south", "VPN tunnels"],
        geeksForGeeks: [{ label: "Network Security", href: "https://www.geeksforgeeks.org/network-security/" }],
        youtube: [{ label: "Search: firewall tutorial", href: yt("network firewall explained") }],
      },
      {
        id: "web-security",
        title: "Web Application Security",
        summary: "OWASP-style: injection, XSS, CSRF, auth flaws.",
        level: "Intermediate",
        duration: "4 h",
        tags: ["websec"],
        studyPoints: ["Parameterized queries", "Output encoding contexts", "CSRF tokens + SameSite"],
        geeksForGeeks: [{ label: "OWASP Top 10", href: "https://www.geeksforgeeks.org/owasp-top-10-vulnerabilities/" }],
        youtube: [{ label: "Search: OWASP Top 10", href: yt("OWASP top 10 explained") }],
      },
      {
        id: "malware",
        title: "Malware & Phishing",
        summary: "Types of malware, phishing indicators, safe habits.",
        level: "Beginner",
        duration: "2 h",
        tags: ["malware"],
        studyPoints: ["Ransomware, trojans, worms", "Email red flags", "User awareness"],
        geeksForGeeks: [{ label: "Types of Malware", href: "https://www.geeksforgeeks.org/types-of-malware/" }],
        youtube: [{ label: "Search: phishing awareness", href: yt("phishing attack explained") }],
      },
      {
        id: "identity-access",
        title: "Identity & Access Management",
        summary: "AuthN vs AuthZ, MFA, OAuth/OIDC basics.",
        level: "Intermediate",
        duration: "3 h",
        tags: ["iam"],
        studyPoints: ["Least privilege", "MFA factors", "Tokens vs sessions"],
        geeksForGeeks: [{ label: "Authentication vs Authorization", href: "https://www.geeksforgeeks.org/difference-between-authentication-and-authorization/" }],
        youtube: [{ label: "Search: OAuth 2 explained", href: yt("OAuth 2.0 explained") }],
      },
      {
        id: "soc-operations",
        title: "SOC & Monitoring",
        summary: "SIEM, alerts, playbooks, log sources.",
        level: "Intermediate",
        duration: "3 h",
        tags: ["soc"],
        studyPoints: ["Correlation rules", "False positives tuning", "Incident tickets"],
        geeksForGeeks: [{ label: "What is SIEM", href: "https://www.geeksforgeeks.org/what-is-siem-security-information-and-event-management/" }],
        youtube: [{ label: "Search: SOC analyst", href: yt("SOC analyst SIEM tutorial") }],
      },
      {
        id: "cloud-security",
        title: "Cloud Security",
        summary: "Shared responsibility, IAM policies, storage exposure.",
        level: "Intermediate",
        duration: "3 h",
        tags: ["cloud"],
        studyPoints: ["Public buckets risk", "IAM boundaries", "CSPM concepts"],
        geeksForGeeks: [{ label: "Cloud Computing Security", href: "https://www.geeksforgeeks.org/cloud-computing-security/" }],
        youtube: [{ label: "Search: AWS shared responsibility", href: yt("AWS shared responsibility model") }],
      },
      {
        id: "risk-compliance",
        title: "Risk & Compliance",
        summary: "Frameworks, policies, audits, privacy basics.",
        level: "Beginner",
        duration: "2 h",
        tags: ["risk"],
        studyPoints: ["Risk register", "GDPR high level", "Policies vs procedures"],
        geeksForGeeks: [{ label: "Risk Management", href: "https://www.geeksforgeeks.org/risk-management-in-information-security/" }],
        youtube: [{ label: "Search: cybersecurity risk management", href: yt("information security risk management") }],
      },
      {
        id: "incident-response",
        title: "Incident Response",
        summary: "Preparation, detection, containment, eradication, recovery.",
        level: "Intermediate",
        duration: "3 h",
        tags: ["incident"],
        studyPoints: ["NIST phases", "Evidence handling", "Comms plan"],
        geeksForGeeks: [{ label: "Incident Response", href: "https://www.geeksforgeeks.org/incident-response-in-cyber-security/" }],
        youtube: [{ label: "Search: incident response NIST", href: yt("NIST incident response") }],
      },
    ],
  },
  {
    id: "net",
    title: "Computer Networks",
    emoji: "🌐",
    gradient: "from-sky-600 via-blue-600 to-indigo-600",
    accent: "text-sky-600 dark:text-sky-400",
    description: "From packets to routing — how the internet actually moves data.",
    topics: [
      {
        id: "osi-tcpip",
        title: "OSI & TCP/IP Models",
        summary: "Layers, encapsulation, protocols per layer.",
        level: "Beginner",
        duration: "2 h",
        tags: ["osi", "tcpip"],
        studyPoints: ["PDU names", "Which device operates where (switch vs router)", "TCP vs UDP placement"],
        geeksForGeeks: [{ label: "OSI Model", href: "https://www.geeksforgeeks.org/layers-of-osi-model/" }],
        youtube: [{ label: "Search: OSI model explained", href: yt("OSI model explained") }],
      },
      {
        id: "ip-subnetting",
        title: "IP Addressing & Subnetting",
        summary: "IPv4, CIDR, masks, private ranges.",
        level: "Intermediate",
        duration: "3 h",
        tags: ["subnetting"],
        studyPoints: ["AND with mask for network address", "/24, /16 intuition", "RFC1918 ranges"],
        geeksForGeeks: [{ label: "Subnetting", href: "https://www.geeksforgeeks.org/subnetting-in-ipv4/" }],
        youtube: [{ label: "Search: subnetting tutorial", href: yt("IP subnetting tutorial") }],
      },
      {
        id: "routing",
        title: "Routing",
        summary: "Static vs dynamic, longest prefix match, default route.",
        level: "Intermediate",
        duration: "3 h",
        tags: ["routing"],
        studyPoints: ["Routing table lookup", "AD/metrics (concept)", "BGP at ISP scale (intro)"],
        geeksForGeeks: [{ label: "Routing in Computer Network", href: "https://www.geeksforgeeks.org/routing-in-computer-network/" }],
        youtube: [{ label: "Search: IP routing explained", href: yt("how IP routing works") }],
      },
      {
        id: "switching",
        title: "Switching & VLANs",
        summary: "L2 forwarding, STP mention, VLAN segmentation.",
        level: "Intermediate",
        duration: "2 h",
        tags: ["switching"],
        studyPoints: ["MAC learning", "Broadcast domains", "Access/trunk (concept)"],
        geeksForGeeks: [{ label: "Switching", href: "https://www.geeksforgeeks.org/switching-in-computer-network/" }],
        youtube: [{ label: "Search: how switches work", href: yt("how network switch works") }],
      },
      {
        id: "tcp-udp",
        title: "TCP & UDP",
        summary: "Ports, handshake, reliability, use cases.",
        level: "Beginner",
        duration: "2 h",
        tags: ["tcp", "tcpip"],
        studyPoints: ["Three-way handshake", "Flow control vs congestion (names)", "UDP for latency-tolerant loss"],
        geeksForGeeks: [{ label: "TCP vs UDP", href: "https://www.geeksforgeeks.org/differences-between-tcp-and-udp/" }],
        youtube: [{ label: "Search: TCP vs UDP", href: yt("TCP vs UDP explained") }],
      },
      {
        id: "dns-dhcp",
        title: "DNS & DHCP",
        summary: "Name resolution, record types, dynamic IP config.",
        level: "Beginner",
        duration: "2 h",
        tags: ["dns", "dhcp"],
        studyPoints: ["A vs AAAA", "Recursive vs authoritative", "DHCP DORA"],
        geeksForGeeks: [
          { label: "DNS", href: "https://www.geeksforgeeks.org/domain-name-system-dns-in-application-layer/" },
          { label: "DHCP", href: "https://www.geeksforgeeks.org/dynamic-host-configuration-protocol-dhcp/" },
        ],
        youtube: [{ label: "Search: how DNS works", href: yt("how DNS works") }],
      },
      {
        id: "http-https",
        title: "HTTP & HTTPS",
        summary: "Methods, status codes, cookies, TLS role.",
        level: "Beginner",
        duration: "2 h",
        tags: ["http", "tcpip"],
        studyPoints: ["GET vs POST", "Stateless + cookies", "HTTPS = HTTP + TLS"],
        geeksForGeeks: [{ label: "HTTP", href: "https://www.geeksforgeeks.org/http-non-persistent-persistent-connection/" }],
        youtube: [{ label: "Search: HTTP explained", href: yt("HTTP protocol explained") }],
      },
      {
        id: "wireless",
        title: "Wireless (Wi‑Fi)",
        summary: "802.11 basics, CSMA/CA, SSID.",
        level: "Beginner",
        duration: "2 h",
        tags: ["wireless"],
        studyPoints: ["Shared medium", "Association to AP", "2.4 vs 5 GHz tradeoffs"],
        geeksForGeeks: [{ label: "WiFi", href: "https://www.geeksforgeeks.org/wifi-technology/" }],
        youtube: [{ label: "Search: WiFi CSMA/CA", href: yt("wifi 802.11 explained") }],
      },
      {
        id: "vpn-firewalls",
        title: "VPNs & Firewalls",
        summary: "Tunnels, policies, NAT traversal (concept).",
        level: "Intermediate",
        duration: "2 h",
        tags: ["vpn", "networksec"],
        studyPoints: ["Site-to-site vs remote access", "Policy zones", "SSL VPN vs IPsec (names)"],
        geeksForGeeks: [{ label: "VPN", href: "https://www.geeksforgeeks.org/types-of-vpn/" }],
        youtube: [{ label: "Search: how VPN works", href: yt("how VPN works") }],
      },
      {
        id: "troubleshooting",
        title: "Troubleshooting Tools",
        summary: "ping, traceroute, dig/nslookup, packet capture intro.",
        level: "Beginner",
        duration: "2 h",
        tags: ["troubleshooting", "dns"],
        studyPoints: ["Layer isolation", "ICMP blocked pitfalls", "Capture filters basics"],
        geeksForGeeks: [{ label: "Traceroute", href: "https://www.geeksforgeeks.org/traceroute-on-network/" }],
        youtube: [{ label: "Search: Wireshark tutorial", href: yt("Wireshark tutorial beginners") }],
      },
    ],
  },
  {
    id: "os",
    title: "Operating Systems",
    emoji: "⚙️",
    gradient: "from-orange-500 via-rose-500 to-pink-600",
    accent: "text-orange-600 dark:text-orange-400",
    description: "Processes, memory, filesystems, and concurrency primitives.",
    topics: [
      {
        id: "processes",
        title: "Processes",
        summary: "PCB, states, fork/exec, context switch.",
        level: "Beginner",
        duration: "2 h",
        tags: ["processes"],
        studyPoints: ["Ready/running/blocked", "fork copy-on-write", "Context switch cost"],
        geeksForGeeks: [{ label: "Process in OS", href: "https://www.geeksforgeeks.org/processes-in-linux/" }],
        youtube: [{ label: "Search: process vs thread OS", href: yt("process vs thread operating system") }],
      },
      {
        id: "threads",
        title: "Threads & Concurrency",
        summary: "User vs kernel threads, races, locks overview.",
        level: "Intermediate",
        duration: "3 h",
        tags: ["threads", "sync"],
        studyPoints: ["Shared address space", "Data races", "Mutex/semaphore names"],
        geeksForGeeks: [{ label: "Threads", href: "https://www.geeksforgeeks.org/threads-in-operating-system/" }],
        youtube: [{ label: "Search: multithreading OS", href: yt("threads operating system") }],
      },
      {
        id: "scheduling",
        title: "CPU Scheduling",
        summary: "FCFS, SJF, RR, priorities, starvation.",
        level: "Intermediate",
        duration: "2 h",
        tags: ["scheduling"],
        studyPoints: ["Preemption", "Turnaround vs waiting time", "Nice values (Linux)"],
        geeksForGeeks: [{ label: "CPU Scheduling", href: "https://www.geeksforgeeks.org/cpu-scheduling-in-operating-systems/" }],
        youtube: [{ label: "Search: CPU scheduling algorithms", href: yt("CPU scheduling algorithms") }],
      },
      {
        id: "memory-mgmt",
        title: "Memory Management",
        summary: "Paging, segmentation, fragmentation.",
        level: "Intermediate",
        duration: "3 h",
        tags: ["memory"],
        studyPoints: ["Physical vs virtual addresses", "Page tables", "Internal vs external fragmentation"],
        geeksForGeeks: [{ label: "Memory Management", href: "https://www.geeksforgeeks.org/memory-management-in-operating-system/" }],
        youtube: [{ label: "Search: paging OS", href: yt("paging memory management OS") }],
      },
      {
        id: "virtual-memory",
        title: "Virtual Memory",
        summary: "Demand paging, page faults, thrashing, replacement.",
        level: "Advanced",
        duration: "3 h",
        tags: ["virtual", "memory"],
        studyPoints: ["LRU concept", "Working set", "Thrashing symptom"],
        geeksForGeeks: [{ label: "Virtual Memory", href: "https://www.geeksforgeeks.org/virtual-memory-in-operating-system/" }],
        youtube: [{ label: "Search: virtual memory explained", href: yt("virtual memory explained") }],
      },
      {
        id: "filesystems",
        title: "File Systems",
        summary: "Files, directories, inodes, journaling.",
        level: "Intermediate",
        duration: "2 h",
        tags: ["filesystem"],
        studyPoints: ["inode metadata", "Hard vs symbolic links", "Journaling recovery"],
        geeksForGeeks: [{ label: "File Systems", href: "https://www.geeksforgeeks.org/file-systems-in-operating-system/" }],
        youtube: [{ label: "Search: inode explained", href: yt("inode file system explained") }],
      },
      {
        id: "deadlocks",
        title: "Deadlocks",
        summary: "Four conditions, avoidance, detection, recovery.",
        level: "Intermediate",
        duration: "2 h",
        tags: ["deadlock"],
        studyPoints: ["Wait-for graph", "Banker’s (concept)", "Kill/preempt strategies"],
        geeksForGeeks: [{ label: "Deadlock", href: "https://www.geeksforgeeks.org/deadlock-in-operating-system/" }],
        youtube: [{ label: "Search: deadlock OS", href: yt("deadlock operating system") }],
      },
      {
        id: "io-subsystem",
        title: "I/O Subsystem",
        summary: "Device drivers, DMA, blocking I/O.",
        level: "Intermediate",
        duration: "2 h",
        tags: ["io"],
        studyPoints: ["DMA offloads CPU", "Blocking vs non-blocking I/O", "Spooling"],
        geeksForGeeks: [{ label: "I/O in OS", href: "https://www.geeksforgeeks.org/io-system-in-operating-system/" }],
        youtube: [{ label: "Search: DMA explained", href: yt("DMA direct memory access") }],
      },
      {
        id: "sync-primitives",
        title: "Synchronization Primitives",
        summary: "Mutex, semaphore, monitors, deadlocks link.",
        level: "Advanced",
        duration: "3 h",
        tags: ["sync"],
        studyPoints: ["Critical section", "Bounded waiting", "Priority inversion (name)"],
        geeksForGeeks: [{ label: "Process Synchronization", href: "https://www.geeksforgeeks.org/process-synchronization/" }],
        youtube: [{ label: "Search: mutex semaphore", href: yt("mutex vs semaphore") }],
      },
      {
        id: "linux-basics",
        title: "Linux Shell & Permissions",
        summary: "Common commands, chmod, processes listing.",
        level: "Beginner",
        duration: "2 h",
        tags: ["linux"],
        studyPoints: ["ls, ps, grep, pipes", "rwx bits", "sudo concept"],
        geeksForGeeks: [{ label: "Linux Tutorial", href: "https://www.geeksforgeeks.org/linux-tutorial/" }],
        youtube: [{ label: "Search: Linux for beginners", href: yt("Linux command line beginners") }],
      },
    ],
  },
  {
    id: "db",
    title: "Databases & SQL",
    emoji: "🗄️",
    gradient: "from-amber-500 via-orange-500 to-red-500",
    accent: "text-amber-600 dark:text-amber-400",
    description: "Relational model, SQL, transactions, and tuning basics.",
    topics: [
      {
        id: "sql-basics",
        title: "SQL Basics",
        summary: "SELECT, WHERE, GROUP BY, HAVING, ORDER BY.",
        level: "Beginner",
        duration: "2 h",
        tags: ["sql"],
        studyPoints: ["Predicate pushdown intuition", "GROUP BY vs WHERE", "NULL handling"],
        geeksForGeeks: [{ label: "SQL Tutorial", href: "https://www.geeksforgeeks.org/sql-tutorial/" }],
        youtube: [{ label: "Search: SQL for beginners", href: yt("SQL tutorial beginners") }],
      },
      {
        id: "joins",
        title: "Joins",
        summary: "INNER, LEFT, RIGHT, FULL, cross products.",
        level: "Beginner",
        duration: "2 h",
        tags: ["joins"],
        studyPoints: ["ON vs WHERE (ANSI)", "NULLs in outer joins", "Join order cost"],
        geeksForGeeks: [{ label: "SQL Joins", href: "https://www.geeksforgeeks.org/sql-join-set-1-inner-left-right-and-full-joins/" }],
        youtube: [{ label: "Search: SQL joins explained", href: yt("SQL joins explained") }],
      },
      {
        id: "normalization",
        title: "Normalization",
        summary: "1NF–3NF, functional dependencies.",
        level: "Intermediate",
        duration: "2 h",
        tags: ["normalization"],
        studyPoints: ["Eliminate redundancy", "Anomalies", "Decomposition"],
        geeksForGeeks: [{ label: "Normalization", href: "https://www.geeksforgeeks.org/normalization-in-dbms/" }],
        youtube: [{ label: "Search: database normalization", href: yt("database normalization 1NF 2NF 3NF") }],
      },
      {
        id: "indexing",
        title: "Indexing",
        summary: "B+ trees, clustered vs non-clustered, covering indexes.",
        level: "Intermediate",
        duration: "2 h",
        tags: ["index"],
        studyPoints: ["Seek vs scan", "Write amplification", "Selectivity"],
        geeksForGeeks: [{ label: "Indexing in DBMS", href: "https://www.geeksforgeeks.org/indexing-in-databases-set-1/" }],
        youtube: [{ label: "Search: database indexes explained", href: yt("database index explained") }],
      },
      {
        id: "transactions",
        title: "Transactions",
        summary: "BEGIN/COMMIT/ROLLBACK, isolation concepts.",
        level: "Intermediate",
        duration: "2 h",
        tags: ["transaction", "acid"],
        studyPoints: ["Atomicity", "Isolation levels names", "Lost update"],
        geeksForGeeks: [{ label: "Transactions in SQL", href: "https://www.geeksforgeeks.org/transaction-isolation-levels-dbms/" }],
        youtube: [{ label: "Search: ACID database", href: yt("ACID properties database") }],
      },
      {
        id: "acid-recovery",
        title: "ACID & Recovery",
        summary: "Logging, WAL, durability.",
        level: "Advanced",
        duration: "2 h",
        tags: ["acid", "transaction"],
        studyPoints: ["Write-ahead logging", "Undo/redo", "Checkpoint"],
        geeksForGeeks: [{ label: "ACID Properties", href: "https://www.geeksforgeeks.org/acid-properties-in-dbms/" }],
        youtube: [{ label: "Search: WAL database", href: yt("write ahead log database") }],
      },
      {
        id: "er-modeling",
        title: "ER Modeling",
        summary: "Entities, relationships, keys, cardinality.",
        level: "Beginner",
        duration: "2 h",
        tags: ["er"],
        studyPoints: ["Weak entities", "Cardinality", "Translate ER → tables"],
        geeksForGeeks: [{ label: "ER Model", href: "https://www.geeksforgeeks.org/introduction-of-er-model/" }],
        youtube: [{ label: "Search: ER diagram tutorial", href: yt("ER diagram database tutorial") }],
      },
      {
        id: "nosql-overview",
        title: "NoSQL Overview",
        summary: "Document, key-value, wide-column, graph — when to use.",
        level: "Beginner",
        duration: "2 h",
        tags: ["nosql"],
        studyPoints: ["CAP reminder", "Schema flexibility", "Eventual consistency"],
        geeksForGeeks: [{ label: "NoSQL Databases", href: "https://www.geeksforgeeks.org/introduction-to-nosql-databases/" }],
        youtube: [{ label: "Search: SQL vs NoSQL", href: yt("SQL vs NoSQL explained") }],
      },
      {
        id: "query-optimization",
        title: "Query Optimization",
        summary: "Plans, statistics, hints (use sparingly).",
        level: "Advanced",
        duration: "2 h",
        tags: ["optimization"],
        studyPoints: ["EXPLAIN concept", "Selectivity", "Avoid SELECT *"],
        geeksForGeeks: [{ label: "Query Optimization", href: "https://www.geeksforgeeks.org/query-optimization-in-relational-algebra/" }],
        youtube: [{ label: "Search: SQL query optimization", href: yt("SQL query optimization explain plan") }],
      },
      {
        id: "db-security",
        title: "Database Security",
        summary: "Authz, injection, encryption at rest, auditing.",
        level: "Intermediate",
        duration: "2 h",
        tags: ["security", "sql"],
        studyPoints: ["Least privilege DB users", "Parameterized queries", "Masking/encryption"],
        geeksForGeeks: [{ label: "Database Security", href: "https://www.geeksforgeeks.org/database-security-in-dbms/" }],
        youtube: [{ label: "Search: database security", href: yt("database security tutorial") }],
      },
    ],
  },
];
