import type { QuizQuestion } from "./types";

function Q(
  domain: string,
  tags: string[],
  question: string,
  options: [string, string, string, string],
  answer: 0 | 1 | 2 | 3,
  concept: string,
  explanation: string,
): QuizQuestion {
  return {
    question,
    options: [...options],
    answer,
    concept,
    explanation,
    tags,
    domain,
  };
}

/** Large shared pool; topics pick 10 by matching tags + deterministic shuffle. */
export const QUESTION_POOL: QuizQuestion[] = [
  // —— DSA ——
  Q("dsa", ["arrays", "complexity"], "Scanning an array once to find max is:", ["O(1)", "O(log n)", "O(n)", "O(n^2)"], 2, "Time complexity", "One pass over n elements is linear."),
  Q("dsa", ["arrays", "twopointers"], "Best approach for pair sum in a sorted array:", ["Brute force only", "Two pointers", "Binary search on value", "Hash map always"], 1, "Two pointers", "Sorted order lets L and R move inward in O(n)."),
  Q("dsa", ["hashmaps"], "Average-case lookup in a hash map is:", ["O(n)", "O(log n)", "O(1)", "O(n^2)"], 2, "Hashing", "With a good hash function, buckets stay small on average."),
  Q("dsa", ["strings"], "Checking if two strings are anagrams (lowercase) often uses:", ["Only sorting", "Frequency map / count array", "Trie only", "DFS"], 1, "String frequency", "Count characters to compare multisets."),
  Q("dsa", ["linkedlists"], "Inserting at head of singly linked list is:", ["O(n)", "O(1)", "O(log n)", "O(n^2)"], 1, "Linked list ops", "Head insert only rewires pointers."),
  Q("dsa", ["stacks"], "Valid parentheses checking typically uses:", ["Queue", "Stack", "Heap", "Graph"], 1, "Stack applications", "Latest open bracket must match next close."),
  Q("dsa", ["queues"], "BFS on unweighted graph uses:", ["Stack", "Queue", "Priority queue only", "Union-find"], 1, "BFS", "Process layer by layer in FIFO order."),
  Q("dsa", ["trees"], "Inorder traversal of a BST visits nodes in:", ["Random order", "Sorted key order", "Reverse sorted", "Heap order"], 1, "BST property", "Left subtree < root < right subtree."),
  Q("dsa", ["trees"], "Height of balanced BST with n nodes is:", ["O(n)", "O(log n)", "O(1)", "O(n^2)"], 1, "Tree balance", "Balanced trees keep depth logarithmic."),
  Q("dsa", ["graphs"], "Detecting cycle in directed graph often uses:", ["Only BFS", "DFS + recursion stack colors", "Dijkstra", "Topological sort only"], 1, "Graph cycle", "Three-color or recursion-stack marking is standard."),
  Q("dsa", ["graphs"], "Dijkstra requires:", ["Negative edges", "Non-negative edge weights", "Unweighted only", "DAG only"], 1, "Shortest paths", "Greedy relaxation fails with negative edges."),
  Q("dsa", ["sorting"], "Merge sort average time:", ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"], 1, "Sorting", "Divide and conquer splits and merges."),
  Q("dsa", ["sorting"], "Quicksort worst case (pivot choice) can be:", ["O(n log n)", "O(n)", "O(n^2)", "O(1)"], 2, "Quicksort", "Bad pivots on sorted input cause unbalanced partitions."),
  Q("dsa", ["searching"], "Binary search needs:", ["Unsorted array", "Sorted array", "Linked list only", "Graph"], 1, "Binary search", "Monotonic split by midpoint."),
  Q("dsa", ["dp"], "Optimal substructure means:", ["Greedy always works", "Optimal solution contains optimal subsolutions", "No overlapping subproblems", "Only trees"], 1, "DP intuition", "Build answer from smaller solved subproblems."),
  Q("dsa", ["dp"], "Fibonacci with memoization avoids:", ["Recursion", "Redundant recomputation", "Base cases", "Linear time"], 1, "Memoization", "Cache results of subproblems."),
  Q("dsa", ["greedy"], "Activity selection (intervals) classic greedy sorts by:", ["Start time only", "Finish time", "Duration", "Random"], 1, "Greedy scheduling", "Earliest finishing leaves max room."),
  Q("dsa", ["complexity"], "Nested loops i,j over n×n is:", ["O(n)", "O(n log n)", "O(n^2)", "O(2^n)"], 2, "Nested loops", "n iterations each of n."),
  Q("dsa", ["graphs"], "Topological order exists iff:", ["Graph has cycle", "DAG", "Complete graph", "Tree only"], 1, "Topological sort", "DAGs model dependencies without cycles."),
  Q("dsa", ["hashmaps"], "Collision resolution with chaining stores:", ["One element per bucket", "Linked list / structure per bucket", "No buckets", "Sorted array globally"], 1, "Hash tables", "Buckets hold collections of colliding keys."),
  Q("dsa", ["strings"], "KMP improves naive substring search by using:", ["Brute force only", "Prefix function to skip shifts", "Sorting", "Hash of entire text"], 1, "String algorithms", "Reuses knowledge of matched prefix."),
  Q("dsa", ["linkedlists"], "Detect cycle in linked list (Floyd):", ["Two pointers different speeds", "Copy list", "Sort nodes", "BFS"], 0, "Cycle detection", "Tortoise and hare meets if cycle exists."),
  Q("dsa", ["trees"], "Preorder traversal order:", ["Left-root-right", "Root-left-right", "Left-right-root", "Level order"], 1, "Tree traversals", "Preorder processes root before subtrees."),
  Q("dsa", ["arrays"], "Prefix sums help answer:", ["Static range sums quickly", "Only max element", "Shortest path", "Sorting only"], 0, "Prefix sum", "Precompute cumulative sums for O(1) ranges."),
  Q("dsa", ["dp"], "0/1 knapsack is typically solved with:", ["Greedy by value", "DP over items and capacity", "BFS", "Union-find"], 1, "Knapsack", "Each item used at most once; DP tracks best value per capacity."),

  // —— Cybersecurity ——
  Q("cyber", ["fundamentals"], "CIA triad includes Confidentiality, Integrity, and:", ["Availability", "Anonymity", "Authenticity only", "Accounting"], 0, "CIA triad", "Classic security goals framework."),
  Q("cyber", ["crypto"], "AES is primarily:", ["Stream cipher", "Block cipher", "Hash function", "Key exchange protocol"], 1, "Symmetric crypto", "AES encrypts fixed-size blocks with keys."),
  Q("cyber", ["crypto"], "SHA-256 is a:", ["Encryption algorithm", "Cryptographic hash", "MAC only", "Random number generator"], 1, "Hashing", "One-way digest of arbitrary-length input."),
  Q("cyber", ["websec"], "Primary defense against SQL injection:", ["Longer passwords", "Parameterized queries / prepared statements", "HTTPS only", "Firewall default deny"], 1, "SQLi prevention", "Separate SQL structure from user data."),
  Q("cyber", ["websec"], "XSS targets:", ["Database integrity", "Browser execution context", "Disk encryption", "BGP tables"], 1, "XSS", "Injected scripts run in victim browser context."),
  Q("cyber", ["networksec"], "TLS provides:", ["Routing", "Confidentiality and integrity on the wire", "DNS resolution", "ARP"], 1, "TLS", "Encrypts and authenticates application data."),
  Q("cyber", ["malware"], "Ransomware typically:", ["Speeds up CPU", "Encrypts data and demands payment", "Only logs keystrokes", "Fixes vulnerabilities"], 1, "Ransomware", "Extortion via data encryption."),
  Q("cyber", ["iam"], "MFA adds security by requiring:", ["Only password", "Multiple independent factors", "Same factor twice", "Public Wi‑Fi"], 1, "MFA", "Something you know/have/are."),
  Q("cyber", ["soc"], "SIEM mainly helps with:", ["Compiler optimization", "Log aggregation and correlation", "GPU rendering", "RAID"], 1, "SOC tools", "Security monitoring and alerting."),
  Q("cyber", ["cloud"], "Shared responsibility model means:", ["Cloud secures everything", "Provider vs customer split of duties", "Customer has no duties", "Only physical security"], 1, "Cloud security", "e.g. AWS secures cloud; you secure in-cloud config."),
  Q("cyber", ["risk"], "Risk = typically:", ["Threat × Vulnerability × Impact (assessment models)", "Only firewall rules", "Only patch count", "Uptime"], 0, "Risk basics", "Combine likelihood and impact."),
  Q("cyber", ["incident"], "First containment step often:", ["Delete logs", "Isolate affected systems", "Announce on social first", "Disable backups"], 1, "Incident response", "Stop spread before eradication."),
  Q("cyber", ["networksec"], "Firewall default stance should often be:", ["Allow all", "Deny by default, allow explicitly", "Mirror ports", "Disable logging"], 1, "Network policy", "Least privilege for traffic."),
  Q("cyber", ["crypto"], "Public-key crypto uses:", ["Same secret key both sides", "Key pair (public/private)", "No keys", "Only XOR"], 1, "Asymmetric crypto", "Different keys for encrypt/sign vs decrypt/verify."),
  Q("cyber", ["websec"], "CSRF tokens help ensure:", ["Password strength", "Request was intentional for user session", "TLS version", "DNSSEC"], 1, "CSRF", "Attacker site cannot guess user-specific token."),
  Q("cyber", ["fundamentals"], "Least privilege means:", ["Max access always", "Minimum access needed for job", "No authentication", "Shared admin"], 1, "Access control", "Reduce blast radius."),
  Q("cyber", ["malware"], "Phishing primarily exploits:", ["CPU bugs", "Human trust / deception", "BGP", "TCP window size"], 1, "Social engineering", "Tricks users into revealing secrets."),
  Q("cyber", ["iam"], "OAuth 2.0 is mainly about:", ["Password storage", "Delegated authorization", "Disk encryption", "Packet routing"], 1, "OAuth", "Apps access resources on user's behalf with tokens."),
  Q("cyber", ["networksec"], "Port scanning discovers:", ["Open services / ports", "CPU temperature", "RAM timings", "Compiler flags"], 0, "Reconnaissance", "Maps attack surface."),
  Q("cyber", ["incident"], "Chain of custody applies to:", ["Network diagrams", "Digital evidence handling", "HR schedules", "SSL certs only"], 1, "Forensics", "Document who handled evidence when."),

  // —— Networks ——
  Q("net", ["osi"], "IP addressing is associated with OSI:", ["Layer 2", "Layer 3", "Layer 4 only", "Layer 7"], 1, "OSI model", "Network layer handles logical addressing."),
  Q("net", ["tcpip"], "TCP is:", ["Connectionless", "Connection-oriented, reliable", "Best-effort only", "Layer 2 protocol"], 1, "TCP", "Handshake, sequencing, retransmission."),
  Q("net", ["tcpip"], "UDP is:", ["Reliable ordered delivery", "Connectionless, best effort", "Always slower than TCP", "Layer 3 routing protocol"], 1, "UDP", "No built-in retransmission."),
  Q("net", ["routing"], "Router forwards using primarily:", ["MAC address table only", "IP destination and routing table", "Application name", "TCP port in isolation"], 1, "Routing", "Longest-prefix match on prefixes."),
  Q("net", ["switching"], "Switch learns MAC addresses via:", ["ARP spoofing", "Examining source MACs on frames", "DNS", "DHCP only"], 1, "Switching", "Builds CAM table from ingress frames."),
  Q("net", ["dns"], "DNS resolves:", ["MAC to IP", "Names to records (e.g. A/AAAA)", "Ports to apps", "Encryption keys"], 1, "DNS", "Distributed name system."),
  Q("net", ["dhcp"], "DHCP assigns:", ["Static routes only", "IP configuration to clients", "TLS certificates", "VLAN IDs only"], 1, "DHCP", "Dynamic host configuration."),
  Q("net", ["wireless"], "Wi‑Fi operates mainly at:", ["Physical/Data link (IEEE 802.11)", "Pure application layer", "Transport only", "Session layer only"], 0, "Wireless", "802.11 defines PHY/MAC."),
  Q("net", ["vpn"], "Site-to-site VPN typically protects:", ["Only ARP", "Traffic between networks over untrusted media", "CPU cache", "RAM"], 1, "VPN", "Tunnel encrypts inter-site traffic."),
  Q("net", ["troubleshooting"], "Ping uses:", ["TCP 443", "ICMP echo", "UDP 53 only", "BGP"], 1, "Connectivity test", "ICMP reachability check."),
  Q("net", ["subnetting"], "/24 IPv4 mask means:", ["255.0.0.0", "255.255.255.0", "255.255.0.0", "/8 only"], 1, "Subnet masks", "24 leading bits for network."),
  Q("net", ["http"], "HTTPS wraps HTTP with:", ["FTP", "TLS", "SMTP", "SNMP"], 1, "HTTP/TLS", "Encryption on port 443 typically."),
  Q("net", ["osi"], "HTTP is generally considered:", ["Layer 2", "Layer 7 application", "Layer 3", "Layer 1"], 1, "OSI mapping", "Application-layer protocol."),
  Q("net", ["routing"], "Default route is often:", ["0.0.0.0/0", "127.0.0.1/32", "10/8", "224.0.0.0/4"], 0, "Default route", "Catch-all when no specific prefix matches."),
  Q("net", ["switching"], "VLANs primarily:", ["Encrypt Wi‑Fi", "Segment broadcast domains at L2", "Replace IP", "Are Layer 3 only"], 1, "VLANs", "Separate L2 domains on shared switches."),
  Q("net", ["tcp"], "TCP three-way handshake uses:", ["SYN, SYN-ACK, ACK", "GET, POST, PUT", "ARP, RARP, GARP", "Hello, DBD, LSR"], 0, "TCP handshake", "Connection establishment."),
  Q("net", ["dns"], "DNSSEC adds:", ["Faster UDP", "Authentication of DNS data", "Always encryption", "MAC learning"], 1, "DNSSEC", "Signatures on records."),
  Q("net", ["troubleshooting"], "traceroute helps reveal:", ["CPU usage", "Path/route taken toward destination", "Disk SMART", "TLS cipher only"], 1, "Traceroute", "Per-hop latency discovery."),
  Q("net", ["wireless"], "CSMA/CA relates to:", ["Ethernet classic CD", "Wireless collision avoidance", "BGP path selection", "NAT"], 1, "802.11 MAC", "Listen before talk; avoid collisions."),
  Q("net", ["vpn"], "Split tunneling means:", ["All traffic via VPN", "Some traffic direct, some via VPN", "No encryption", "Double NAT only"], 1, "VPN policy", "Selective tunneling."),

  // —— Operating systems ——
  Q("os", ["processes"], "A process is:", ["A lightweight execution unit sharing heap by default", "Program in execution with its resources", "Only kernel thread", "DNS record"], 1, "Processes", "OS abstraction for running program."),
  Q("os", ["threads"], "Threads of same process share:", ["Nothing", "Address space; have own stacks/registers", "Only disk", "Separate page tables always"], 1, "Threads", "Share code/data; independent execution contexts."),
  Q("os", ["scheduling"], "Preemptive scheduling can switch:", ["Never while running user code", "Running process involuntarily on timer/interrupt", "Only at program exit", "Only on I/O completion"], 1, "CPU scheduling", "Timer interrupt forces context switch."),
  Q("os", ["memory"], "Virtual memory allows:", ["Only physical RAM use", "Processes to use logical address space larger than RAM", "No paging", "Disabling MMU"], 1, "Virtual memory", "Demand paging + backing store."),
  Q("os", ["virtual"], "Page fault on valid page not in RAM leads to:", ["Crash always", "Load page from backing store", "Ignore", "Kill all threads"], 1, "Paging", "OS fetches page then resumes."),
  Q("os", ["filesystem"], "Inode typically stores:", ["File data bytes only", "Metadata and block pointers", "Process PCB", "CPU registers"], 1, "File systems", "Unix-style metadata structure."),
  Q("os", ["deadlock"], "Deadlock requires (Coffman): mutual exclusion, hold-wait, no preemption, and:", ["Single CPU", "Circular wait", "Many threads", "SSD"], 1, "Deadlock conditions", "Cycle in resource allocation graph."),
  Q("os", ["io"], "DMA helps by:", ["CPU copying every byte", "Device transfers to memory with less CPU involvement", "Replacing interrupts", "Disabling caches"], 1, "I/O", "Offload bulk transfers."),
  Q("os", ["sync"], "Mutex vs semaphore (typical): mutex for:", ["Counting many instances", "Mutual exclusion binary lock", "CPU scheduling", "Disk scheduling"], 1, "Synchronization", "Mutex ~ binary semaphore with ownership rules."),
  Q("os", ["linux"], "`chmod +x` affects:", ["Network mask", "File execute permission bits", "Kernel version", "Inode count"], 1, "Linux permissions", "rwx bits for user/group/other."),
  Q("os", ["processes"], "fork() in Unix creates:", ["Thread only", "Child process copy-on-write", "Socket pair", "VLAN"], 1, "fork", "New process duplicates address space lazily."),
  Q("os", ["scheduling"], "Round-robin uses:", ["Static priority only", "Time quantum per process", "Shortest job first always", "Random"], 1, "RR scheduling", "Fair CPU sharing."),
  Q("os", ["memory"], "TLB caches:", ["Disk blocks", "Page table translations", "DNS entries", "TCP windows"], 1, "TLB", "Speeds virtual→physical lookup."),
  Q("os", ["filesystem"], "Journaling in filesystems helps:", ["Faster CPU", "Crash consistency / recovery", "Wi‑Fi speed", "TLS"], 1, "Journaling FS", "Log metadata changes before commit."),
  Q("os", ["sync"], "Deadlock avoidance (Banker's) needs:", ["No resources", "Max claims and safe sequence check", "Only one process", "UDP"], 1, "Banker's algorithm", "Simulate allocation to ensure safe state."),
  Q("os", ["threads"], "Race condition happens when:", ["Single-threaded program", "Outcome depends on interleaving without sync", "Using immutable data only", "Read-only FS"], 1, "Concurrency bugs", "Shared mutable state unsynchronized."),
  Q("os", ["linux"], "Kernel space vs user space separates:", ["Nothing", "Privilege levels / protection rings", "Only GUI", "DNS zones"], 1, "Protection", "Syscalls gate privileged operations."),
  Q("os", ["io"], "Spooling is used for:", ["CPU cache lines", "Buffering jobs for devices like printers", "Routing tables", "TLS handshakes"], 1, "Spooling", "Queue jobs for slow devices."),
  Q("os", ["virtual"], "Thrashing indicates:", ["Too many page faults / insufficient frames", "Perfect memory use", "Fast disk", "No swapping"], 0, "Thrashing", "System spends time paging not computing."),
  Q("os", ["deadlock"], "Breaking deadlock via preemption means:", ["Always safe", "Forcibly take resources (may be hard)", "Add circular wait", "Disable mutexes"], 1, "Deadlock handling", "One recovery strategy."),

  // —— Databases ——
  Q("db", ["sql"], "SQL `SELECT` retrieves:", ["Schema only", "Rows from tables/views", "Indexes only", "Triggers only"], 1, "SQL basics", "Query language for relational data."),
  Q("db", ["joins"], "INNER JOIN returns rows:", ["All from left including non-matches", "Matches in both tables per ON", "Cartesian always", "Only nulls"], 1, "Joins", "Intersection on join predicate."),
  Q("db", ["normalization"], "1NF eliminates:", ["Transitive dependencies", "Repeating groups / atomicity violations", "Foreign keys", "Primary keys"], 1, "Normal forms", "Atomic columns; no repeating groups."),
  Q("db", ["index"], "B+ tree index helps:", ["Slower writes always", "Faster lookups/range scans", "Remove need for tables", "Replace SQL"], 1, "Indexing", "Logarithmic height tree."),
  Q("db", ["transaction"], "ACID 'A' is:", ["Atomicity", "Availability", "Aggregation", "Authentication"], 0, "ACID", "All-or-nothing transactions."),
  Q("db", ["acid"], "Isolation prevents:", ["Indexes", "Anomalies from concurrent transactions", "Backups", "Views"], 1, "Isolation levels", "Dirty reads, etc. depending on level."),
  Q("db", ["er"], "ER model captures:", ["Only SQL syntax", "Entities, relationships, constraints", "TCP ports", "CPU scheduling"], 1, "ER modeling", "Conceptual database design."),
  Q("db", ["nosql"], "Document store (e.g. Mongo) typically:", ["Fixed strict schema always", "Stores JSON-like documents", "No scalability", "Only graph queries"], 1, "NoSQL", "Flexible schema per document."),
  Q("db", ["optimization"], "Query planner chooses:", ["Random order", "Estimated-cost execution plan", "Always full scan", "Only index scan"], 1, "Query optimization", "Uses statistics and cost model."),
  Q("db", ["security"], "SQL injection is mitigated by:", ["String concat in query", "Parameterized queries", "Disabling SSL", "More indexes"], 1, "DB security", "Bind parameters separate from SQL text."),
  Q("db", ["joins"], "LEFT JOIN keeps:", ["Only right non-matching", "All left rows, nulls for missing right", "Inner only", "Symmetric difference"], 1, "Outer join", "Preserve left table rows."),
  Q("db", ["normalization"], "3NF removes:", ["Only duplicate rows", "Transitive functional dependencies on non-key", "Primary keys", "Foreign keys"], 1, "3NF", "Non-key attrs depend only on key."),
  Q("db", ["transaction"], "COMMIT:", ["Rolls back changes", "Makes transaction durable (with logging)", "Deletes table", "Locks forever"], 1, "Transactions", "Persist committed work."),
  Q("db", ["index"], "Covering index can:", ["Avoid table access for some queries", "Always slower", "Replace primary key", "Disable writes"], 0, "Covering index", "Index includes all selected columns."),
  Q("db", ["sql"], "Primary key enforces:", ["Optional duplicates", "Uniqueness and non-null (typically)", "No relations", "Weak typing"], 1, "Keys", "Row identity."),
  Q("db", ["acid"], "Durability usually via:", ["RAM only", "Write-ahead logging / media persistence", "UDP", "ICMP"], 1, "Durability", "Survive crashes after commit."),
  Q("db", ["nosql"], "CAP theorem tradeoffs involve:", ["Only SQL", "Consistency, availability, partition tolerance", "Only RAID", "Only TCP"], 1, "CAP", "Distributed systems constraints."),
  Q("db", ["er"], "Cardinality in ER describes:", ["Disk RPM", "Number mapping between entity sets", "Index depth", "Query cost"], 1, "Cardinality", "1:1, 1:N, M:N relationships."),
  Q("db", ["optimization"], "Full table scan may win when:", ["Very selective predicate on indexed column", "Large fraction of rows read / tiny table", "Always never", "Only with views"], 1, "Scan vs index", "Optimizer cost-based choice."),
  Q("db", ["security"], "Least privilege for DB users means:", ["DBA for everyone", "Grant minimum needed permissions", "PUBLIC ALL", "Disable auditing"], 1, "DB hardening", "Reduce insider/bug blast radius."),
];
